#!/usr/bin/env python

import os
import shutil
import pandas as pd

sup_tabs_directory = os.path.realpath(os.path.dirname(__file__))
main_directory = os.path.realpath(os.path.join(sup_tabs_directory, os.pardir))

sup_tabs_latex = os.path.join(main_directory, "suptabs.tex")
pre_latex = os.path.join(sup_tabs_directory, "pre.tex")
post_latex = os.path.join(sup_tabs_directory, "post.tex")

catalog_filename = os.path.join(sup_tabs_directory, "catalog.tsv")
order_filename = os.path.join(sup_tabs_directory, "order.tsv")

catalog = pd.read_csv(catalog_filename, sep="\t")
order = pd.read_csv(order_filename, sep="\t")

catalog = catalog.merge(order)
catalog.sort_values("order", inplace=True)

with open(sup_tabs_latex, "w") as fout:
  fout.write("%AUTOGENERATED - do not edit\n\n")

  with open(pre_latex) as f:
    shutil.copyfileobj(f, fout)

  for table_filename, latex_filename in catalog[["table_filename", "latex_filename"]].values:
    fout.write("\n% {}\n".format(table_filename))

    latex_filename = os.path.join(sup_tabs_directory, latex_filename)

    with open(latex_filename) as f:
      shutil.copyfileobj(f, fout)

  with open(post_latex) as f:
    shutil.copyfileobj(f, fout)
